<script></script>

<template>
  <div class="flex gap-4 rounded-lg mt-8 bg-white">
    <div class="p-2 flex">
      <div>
        <img
          class="h-24 mb-2"
          src="https://icms-image.slatic.net/images/ims-web/b74326bc-4c58-4ebf-9220-6b5619ffc73b.png"
          alt=""
        />
        <p>Wholesale Price</p>
      </div>
    </div>
    <div class="p-2">
      <img
        class="h-24 mb-2"
        src="https://icms-image.slatic.net/images/ims-web/1bcd72dd-8bbb-4893-b346-6ed9fe7233f9.png"
        alt=""
      />
      <p>Everyday Low Price</p>
    </div>
    <div class="p-2">
      <img
        class="h-24 mb-2"
        src="https://icms-image.slatic.net/images/ims-web/6487b832-3919-4bd1-b467-d0aa2e9cfa22.png"
        alt=""
      />
      <p>Fashion</p>
    </div>
    <div class="p-2">
      <img
        class="h-24 mb-2"
        src="https://icms-image.slatic.net/images/ims-web/4f2f87dc-6797-4825-9293-cfc9431fe304.png"
        alt=""
      />
      <p>Beauty & Glamour</p>
    </div>
    <div class="p-2">
      <img
        class="h-24 mb-2"
        src="https://icms-image.slatic.net/images/ims-web/0ec06ff7-4a45-44c4-b8f5-ee3d1fb7d78e.png"
        alt=""
      />
      <p>Mart</p>
    </div>
    <div class="p-2">
      <img
        class="h-24 mb-2"
        src="https://icms-image.slatic.net/images/ims-web/98e538ca-57b3-45c6-8824-16e029e45d38.png"
        alt=""
      />
      <p>Home Makeover</p>
    </div>
    <div class="p-2">
      <img
        class="h-24 mb-2"
        src="https://icms-image.slatic.net/images/ims-web/bba7d001-4a00-4d39-8785-e86fb6bbb7d7.png"
        alt=""
      />
      <p>Free Delivery</p>
    </div>
    <div class="p-2">
      <img
        class="h-24 mb-2"
        src="https://icms-image.slatic.net/images/ims-web/439492ee-8936-40f8-978b-2c5869465e19.png"
        alt=""
      />
      <p>Best Price</p>
    </div>
    <div class="p-2">
      <img
        class="h-24 mb-2"
        src="https://icms-image.slatic.net/images/ims-web/e6e3b765-a1c1-4c5f-961a-c5ce80d8ba3b.png"
        alt=""
      />
      <p>Daraz Visa Card</p>
    </div>
  </div>
</template>

<style></style>
